Add automated tests
ModelSurge/sd-webui-comfyui pull request #13
Opened 2023-03-21 08:42 UTC by ljleb

Closes #12

2023-03-21 13:51 UTC, John-WL approved these changes
we tested the pipeline and it works, we can merge this

2023-03-21 14:10 UTC, John-WL requested changes
Can we add tests for downloading the ComfyUI repo and running it to see if it works?

2023-03-22 01:44 UTC, ljleb commented
We can. I don't want to make this PR too big, maybe merhe and add these in another PR.

2023-03-22 03:30 UTC, John-WL approved these changes

2023-03-22 03:31 UTC, merged